apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tssc-jenkins
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tssc-jenkins 
  name: tssc-jenkins
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tssc-jenkins 
